# Generated by Django 5.0.6 on 2024-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("option", "0004_index_chain_strike_price_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="index",
            name="angel_token",
            field=models.CharField(
                default="", max_length=200, verbose_name="Angel Token"
            ),
        ),
        migrations.AddField(
            model_name="index",
            name="exchange",
            field=models.CharField(default="", max_length=200, verbose_name="Exchange"),
        ),
    ]
